### ISSUE TITLE
when i running your code, there occur a KeyError problem

### ISSUE THREAD

**Issue by JoshSmith0118** [zzxslp/WCL#2]
the problem is as following：
  File "/Users/shihaozhe/WCL-main/modules/datasets.py", line 57, in __getitem__
    label = example['label']
KeyError: 'label'

when I check the annotation.json, I don't find the label too , so how do I solve this problem, what does the label mean? any suggestions? 
hoping for your reply, thx.

**Comment by zzxslp** [comment]
Please check the updated data source.
